export const ServiceTypeEnum = Object.freeze({
  // Home Services
  PLUMBING: 'PLUMBING',
  ELECTRICAL: 'ELECTRICAL',
  CARPENTRY: 'CARPENTRY',
  PAINTING: 'PAINTING',
  CLEANING: 'CLEANING',
  DEEP_CLEANING: 'DEEP_CLEANING',
  SOFA_CLEANING: 'SOFA_CLEANING',
  BATHROOM_CLEANING: 'BATHROOM_CLEANING',
  KITCHEN_CLEANING: 'KITCHEN_CLEANING',

  APPLIANCE_REPAIR: 'APPLIANCE_REPAIR',
  REFRIGERATOR_REPAIR: 'REFRIGERATOR_REPAIR',
  WASHING_MACHINE_REPAIR: 'WASHING_MACHINE_REPAIR',
  MICROWAVE_REPAIR: 'MICROWAVE_REPAIR',
  TV_REPAIR: 'TV_REPAIR',

  PEST_CONTROL: 'PEST_CONTROL',
  WATER_PURIFIER_SERVICE: 'WATER_PURIFIER_SERVICE',
  INVERTER_BATTERY_SERVICE: 'INVERTER_BATTERY_SERVICE',
  CHIMNEY_CLEANING: 'CHIMNEY_CLEANING',
  AC_SERVICE: 'AC_SERVICE',
  GEYSER_REPAIR: 'GEYSER_REPAIR',

  // Installation Services
  AC_INSTALLATION: 'AC_INSTALLATION',
  TV_WALL_MOUNTING: 'TV_WALL_MOUNTING',
  WATER_PURIFIER_INSTALLATION: 'WATER_PURIFIER_INSTALLATION',
  GEYSER_INSTALLATION: 'GEYSER_INSTALLATION',
  FAN_INSTALLATION: 'FAN_INSTALLATION',
  LIGHT_INSTALLATION: 'LIGHT_INSTALLATION',

  // Household Help
  MAID_SERVICE: 'MAID_SERVICE',
  COOK_SERVICE: 'COOK_SERVICE',
  BABYSITTER: 'BABYSITTER',
  ELDERLY_CARE: 'ELDERLY_CARE',
  DRIVER_ON_HIRE: 'DRIVER_ON_HIRE',

  // Personal Care
  MENS_SALON: 'MENS_SALON',
  WOMENS_SALON: 'WOMENS_SALON',
  MASSAGE_THERAPY: 'MASSAGE_THERAPY',
  MEHENDI: 'MEHENDI',
  BRIDAL_MAKEUP: 'BRIDAL_MAKEUP',
  HAIR_STYLING: 'HAIR_STYLING',

  // Health & Wellness
  PHYSIOTHERAPY: 'PHYSIOTHERAPY',
  DOCTOR_HOME_VISIT: 'DOCTOR_HOME_VISIT',
  NURSE_CARETAKER: 'NURSE_CARETAKER',
  DIETICIAN: 'DIETICIAN',
  YOGA_TRAINER: 'YOGA_TRAINER',
  FITNESS_TRAINER: 'FITNESS_TRAINER',

  // Education
  HOME_TUTOR: 'HOME_TUTOR',
  MUSIC_CLASSES: 'MUSIC_CLASSES',
  DANCE_CLASSES: 'DANCE_CLASSES',
  ART_CLASSES: 'ART_CLASSES',
  SPOKEN_ENGLISH: 'SPOKEN_ENGLISH',
  COMPUTER_CLASSES: 'COMPUTER_CLASSES',

  // Vehicles
  CAR_WASHING: 'CAR_WASHING',
  BIKE_SERVICE: 'BIKE_SERVICE',
  PUNCTURE_REPAIR: 'PUNCTURE_REPAIR',
  DRIVING_LESSONS: 'DRIVING_LESSONS',
  CAR_MECHANIC: 'CAR_MECHANIC',
  BATTERY_REPLACEMENT: 'BATTERY_REPLACEMENT',

  // Electronics & IT
  COMPUTER_REPAIR: 'COMPUTER_REPAIR',
  LAPTOP_REPAIR: 'LAPTOP_REPAIR',
  MOBILE_REPAIR: 'MOBILE_REPAIR',
  WIFI_SETUP: 'WIFI_SETUP',
  CCTV_INSTALLATION: 'CCTV_INSTALLATION',

  // Events & Misc
  PHOTOGRAPHY: 'PHOTOGRAPHY',
  VIDEOGRAPHY: 'VIDEOGRAPHY',
  CATERING: 'CATERING',
  TENT_DECORATION: 'TENT_DECORATION',
  DJ_SOUND: 'DJ_SOUND',
  EVENT_PLANNING: 'EVENT_PLANNING',
  FLOWER_DECORATION: 'FLOWER_DECORATION',

  // Logistics
  PACKERS_AND_MOVERS: 'PACKERS_AND_MOVERS',
  COURIER_PICKUP: 'COURIER_PICKUP',
  GOODS_TRANSPORT: 'GOODS_TRANSPORT',

  // Construction & Renovation
  TILING: 'TILING',
  MARBLE_WORK: 'MARBLE_WORK',
  GRANITE_WORK: 'GRANITE_WORK',
  FALSE_CEILING: 'FALSE_CEILING',
  WATERPROOFING: 'WATERPROOFING',
  INTERIOR_DESIGN: 'INTERIOR_DESIGN',
  CIVIL_CONTRACTOR: 'CIVIL_CONTRACTOR',
  HOUSE_RENOVATION: 'HOUSE_RENOVATION',
  MODULAR_KITCHEN: 'MODULAR_KITCHEN',
  ALUMINIUM_WORK: 'ALUMINIUM_WORK',
  GLASS_WORK: 'GLASS_WORK',
  WELDING: 'WELDING',
  BOREWELL_SERVICE: 'BOREWELL_SERVICE',
});

export const BookingStatusEnum = Object.freeze({
  REQUESTED: 'REQUESTED',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED',
  RESCHEDULEDANDAPPROVED: 'RESCHEDULEDANDAPPROVED',
});

export const PaymentStatusEnum = Object.freeze({
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
});

export const UserTypeEnum = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
});
export const UserRoleEnum = Object.freeze({
  USER: 'USER',
  ADMIN: 'ADMIN',
});
export const ListingStatusEnum = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
});

export const CancelledByEnum = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
});

export const DeletionRequestEnum = Object.freeze({
  NONE: 'NONE',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});
