export const ServiceTypeEnum = Object.freeze({
  // Home Services
  PLUMBING: 'PLUMBING',
  ELECTRICAL: 'ELECTRICAL',
  CARPENTRY: 'CARPENTRY',
  PAINTING: 'PAINTING',
  CLEANING: 'CLEANING',
  APPLIANCE_REPAIR: 'APPLIANCE_REPAIR',
  PEST_CONTROL: 'PEST_CONTROL',
  WATER_PURIFIER_SERVICE: 'WATER_PURIFIER_SERVICE',
  INVERTER_BATTERY_SERVICE: 'INVERTER_BATTERY_SERVICE',
  CHIMNEY_CLEANING: 'CHIMNEY_CLEANING',
  AC_SERVICE: 'AC_SERVICE',
  GEYSER_REPAIR: 'GEYSER_REPAIR',

  // Personal Care
  MENS_SALON: 'MENS_SALON',
  WOMENS_SALON: 'WOMENS_SALON',
  MASSAGE_THERAPY: 'MASSAGE_THERAPY',
  MEHENDI: 'MEHENDI',

  // Health & Wellness
  PHYSIOTHERAPY: 'PHYSIOTHERAPY',
  DOCTOR_HOME_VISIT: 'DOCTOR_HOME_VISIT',
  NURSE_CARETAKER: 'NURSE_CARETAKER',
  DIETICIAN: 'DIETICIAN',

  // Education
  HOME_TUTOR: 'HOME_TUTOR',
  MUSIC_CLASSES: 'MUSIC_CLASSES',
  SPOKEN_ENGLISH: 'SPOKEN_ENGLISH',

  // Vehicles
  CAR_WASHING: 'CAR_WASHING',
  BIKE_SERVICE: 'BIKE_SERVICE',
  PUNCTURE_REPAIR: 'PUNCTURE_REPAIR',
  DRIVING_LESSONS: 'DRIVING_LESSONS',

  // Events & Misc
  PHOTOGRAPHY: 'PHOTOGRAPHY',
  CATERING: 'CATERING',
  TENT_DECORATION: 'TENT_DECORATION',
  DJ_SOUND: 'DJ_SOUND',
  PACKERS_AND_MOVERS: 'PACKERS_AND_MOVERS',
  COURIER_PICKUP: 'COURIER_PICKUP',

  // Construction & Renovation
  TILING: 'TILING',
  FALSE_CEILING: 'FALSE_CEILING',
  WATERPROOFING: 'WATERPROOFING',
  INTERIOR_DESIGN: 'INTERIOR_DESIGN',
});

export const BookingStatusEnum = Object.freeze({
  REQUESTED: 'REQUESTED',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED',
  RESCHEDULEDANDAPPROVED: 'RESCHEDULEDANDAPPROVED',
});

export const PaymentStatusEnum = Object.freeze({
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
});

export const UserTypeEnum = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
});
export const UserRoleEnum = Object.freeze({
  USER: 'USER',
  ADMIN: 'ADMIN',
});
export const ListingStatusEnum = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
});

export const CancelledByEnum = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
  ADMIN: 'ADMIN',
});

export const DeletionRequestEnum = Object.freeze({
  NONE: 'NONE',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});
export const NavigationTabEnum = {
  SEARCH: 'SEARCH',
  MY_BOOKINGS: 'MY_BOOKINGS',
  JOBS: 'JOBS',
  EDIT_LISTINGS: 'EDIT_LISTINGS',
  OVERVIEW: 'OVERVIEW',
  USERS: 'USERS',
  CREATE_LISTINGS: 'CREATE_LISTINGS',
};
